project:
  type: book
  output-dir: docs

book:
  title: "Provider: R for Healthcare Administrative Data Analysis"
  reader-mode: true
  author: "Andrew Bruce, RHIT, CPC, CPPM"
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://andrewallenbruce.github.io/provider_book/
  repo-url: https://github.com/andrewallenbruce/provider_book
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - npi.qmd
    - nppes.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

