project:
  type: book
  output-dir: docs
execute:
  freeze: auto

book:
  title: "Provider: R for Healthcare Administrative Data Analysis"
  author: "Andrew Bruce"
  navbar:
    pinned: true
  open-graph: true
  twitter-card:
    creator: "@aabrucehimni"
  page-footer:
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://andrewallenbruce.github.io/provider_book/
  repo-url: https://github.com/andrewallenbruce/provider_book
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Identifiers"
      chapters: 
        - npi.qmd
        - taxonomy.qmd
        - enroll_id.qmd
    - part: "Data Sources"
      chapters: 
        - nppes.qmd
        - qpp.qmd
    - part: "Use Cases"
      chapters: 
        - claims_forms.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
  pdf:
    documentclass: scrreprt

editor: source

