# Introduction

You're feeling good- you are on the road to starting a private SLP practice and you have your ducks in a row. You have your EIN and NPI, and you're credentialed with a few insurance plans. You get ready to bill for your first insurance session- and see boxes 24J, 33A, and 33B on the CMS 1500 claim form. They all say "NPI" or "Identifier." What does it mean? Do you need to put the same number in each box? 

Billing can be confusing, but I can help you figure out what the different types of NPI numbers are and what they mean. 

An NPI number- short for National Provider Identifier- is basically an ID number. It is issued by the CMS (Centers for Medicare and Medicaid Services) to identify individual healthcare providers, and was created as part of HIPAA regulations. It is specific to you, not the job you're in, so it stays the same whether you're in the schools, a medical facility, or a private practice. To check if you have an NPI, visit the NPPES website. 

# What Type of NPI Do You Need?

If you are going to bill insurance - even indirectly by providing a superbill for clients to submit for Out of Network reimbursement- you DO need an NPI. So, which type of NPI do you need?

There are two types of NPI numbers:

Type 1: Individual/Personal NPI

Type 2: Organizational/Group NPI

In general, if you are a solo practitioner, you will just need a Type 1 NPI- UNLESS you have a single-member LLC/PLLC and plan to accept Medicare. 

In that case, you will also need to apply for a Type 2 NPI for your LLC- even though there is only one of you, an LLC is considered a "group/organization."

Where to Put a Type 2 NPI on the CMS 1500 form
So, now that you have those numbers, what do you do with them? You put them on  your CMS 1500 claim forms and superbills, and they will be your unique identifier with any insurance company you are credentialed with. Until you have them memorized, write them down- I use the Important Business Info page from my Private Practice Foundations Course handbook. 

When you are filling out the CMS 1500 form, your Type 1 (individual) NPI will go in box 24J- "Rendering Provider ID". This is the box for whomever actually rendered (provided) the service being billed.

Your Type 2 NPI will go in box 32A- "Service Facility Location Information", again, IF you have an LLC or other group business structure (partnership, S- or C-corp, etc). This even applies to single-member LLCs. 

If you are a sole proprietor/solo practitioner and don't have an LLC or other business structure, you'll use your Type 1 NPI in this box. You use your private practice location address for this box, even if you see clients in their homes.

You can choose if you would like to use your Type 1 or Type 2 NPI in Box 33A- "Billing Provider Info"- if you have a Type 2, use that. If you don’t, use your Type 1.  This box just tells the insurance company who the "pay to" person/organization is, so make sure all of the info is correct so they can get you your money. 