# NPI {.unnumbered}

A National Provider Identifier (NPI) is a unique 10-digit identification number issued to health care providers in the United States by the Centers for Medicare and Medicaid Services (CMS). The NPI has replaced the Unique Physician Identification Number (UPIN) as the required identifier for Medicare services, and is used by other payers, including commercial healthcare insurers. The transition to the NPI was mandated as part of the Administrative Simplifications portion of the Health Insurance Portability and Accountability Act of 1996 (HIPAA).

HIPAA–covered entities such as providers completing electronic transactions, healthcare clearinghouses, and large health plans were required by regulation to use only the NPI to identify covered healthcare providers by May 23, 2007. CMS subsequently announced that as of May 23, 2008, CMS will not impose penalties on covered entities that deploy contingency plans to facilitate the compliance of their trading partners (e.g., those healthcare providers who bill them). The posted guidance document can be used by covered entities to design and implement a contingency plan. Details are contained in a CMS document entitled, "Guidance on Compliance with the HIPAA National Provider Identifier (NPI) Rule." Small health plans have one additional year to comply.

All individual HIPAA–covered healthcare providers or organizations must obtain an NPI for use in all HIPAA standard transactions, even if a billing agency prepares the transaction. Individual HIPAA–covered healthcare providers include physicians, pharmacists, physician assistants, midwives, nurse practitioners, nurse anesthetists, dentists, denturists, licensed opticians, optometrists, chiropractors, clinical social workers, professional counselors, physical therapists, occupational therapists, prosthetists, orthotists, pharmacy technicians and athletic trainers. Organizations include hospitals, home health care agencies, nursing homes, residential treatment centers, group practices, laboratories, pharmacies and medical equipment companies. Once assigned, a provider's NPI is permanent and remains with the provider regardless of job or location changes.

Other health industry workers who provide support services but not health care (such as admissions and medical billing personnel, housekeeping staff and orderlies) are not required to obtain an NPI.

The NPI must be used in connection with the electronic transactions identified in HIPAA. In addition, the NPI may be used in several other ways:

by health care providers to identify themselves in health care transactions identified in HIPAA or on related correspondence;
by health care providers to identify other health care providers in health care transactions or on related correspondence;
by health care providers on prescriptions (however, the NPI will not replace requirements for the DEA number or state license number);
by health plans in their internal provider files to process transactions and communicate with health care providers;
by health plans to coordinate benefits with other health plans;
by health care clearinghouses in their internal files to create and process standard transactions and to communicate with health care providers and health plans;
by electronic patient record systems to identify treating health care providers in patient medical records;
by the Department of Health and Human Services to cross reference health care providers in fraud and abuse files and other program integrity files;
for any other lawful activity requiring individual identification.

The NPI number can be obtained online through the National Plan and Provider Enumeration System (NPPES) pages on CMS's website.[3] Turnaround time for obtaining a number is from 1 to 20 days. NPI numbers can be searched on the CMS website listed in external links 'National Plan and Provider Enumeration System information from CMS'.

<br>