# Taxonomy {.unnumbered}

The Health Care Provider Taxonomy code set is an external, nonmedical data code set designed for use in an electronic environment, specifically within the ASC X12N Health Care transactions. This includes the transactions mandated under HIPAA.

The taxonomy code is a unique alphanumeric code, ten characters in length. The code set is structured into 3 distinct “Levels” including Provider Grouping, Classification, and Area of Specialization.

Level I, Provider Grouping
A major grouping of service(s) or occupation(s) of health care providers. For example: Allopathic & Osteopathic Physicians, Dental Providers, Hospitals, etc.

Level II, Classification
A more specific service or occupation related to the Provider Grouping. For example, the Classification for Allopathic & Osteopathic Physicians is based upon the General Specialty Certificates as issued by the appropriate national boards. The following boards will however, have their general certificates appear as Level III areas of specialization strictly due to display limitations of the code set for Boards that have multiple general certificates: Medical Genetics, Preventive Medicine, Psychiatry & Neurology, Radiology, Surgery, Otolaryngology, Pathology.

Level III, Area of Specialization
A more specialized area of the Classification in which a provider chooses to practice or make services available. For example, the Area of Specialization for provider grouping Allopathic & Osteopathic Physicians is based upon the Subspecialty Certificates as issued by the appropriate national boards.

A taxonomy code is a code that describes the health care service provider's type, classification, and the area of specialization. The primary specialty for this provider is indicated as (Primary) below. The taxonomy codes are selected by the provider at the time of NPI registration. Selection of a taxonomy code does not replace any credentialing or validation process that the provider requesting the code should complete.